import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { lookup, locate } from './lookup.mjs';
const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, 'test-work', crypto.randomUUID()), game = path.join(root,'game');
const put = (file, text) => { fs.mkdirSync(path.dirname(file),{recursive:true}); fs.writeFileSync(file,text); };
put(path.join(game,'launcher-settings.json'),JSON.stringify({rawVersion:'v1.37.5.0'}));
const mission = '# comment\nseries = {\n slot = 1\n first = {\n  position = 1\n  effect = {\n   country_event = { id = example.1 }\n  }\n }\n}\n';
put(path.join(game,'missions/example.txt'),mission);
put(path.join(game,'events/example.txt'),'country_event = {\n id = example.1\n title = example.1.t\n option = {\n  name = example.1.a\n  swap_non_generic_missions = yes\n }\n}\n');
put(path.join(game,'localisation/example_l_english.yml'),'l_english:\n example.1.t:0 "A reference title"\n');
const env = { root, game }, call = (action,opts) => lookup(action,opts,env);
assert.equal(call('search',{query:'country_event'}).totalMatches,2);
assert.equal(call('search',{query:'COUNTRY_EVENT',folder:'missions'}).totalMatches,1);
assert.equal(call('search',{query:'country_event',definitionsOnly:true}).totalMatches,2);
assert.equal(call('search',{query:'example.1',limit:1}).truncated,true);
const references = call('links',{query:'example.1'});
assert.equal(references.totalMatches,2,'Identifier lookup matched localisation suffixes');
const shown = call('show',{file:'missions/example.txt',line:7});
assert.deepEqual(shown.chain.map(node=>node.key),['series','first','effect','country_event']);
assert.equal(shown.block.startLine,4); assert.equal(shown.block.endLine,9);
assert.equal(locate('a = { broken','events/broken.txt',1).parseWarning.includes('Unclosed'),true);
assert.throws(()=>call('show',{file:'../outside.txt'}),/escapes/);
assert.throws(()=>call('save',{file:'missions/example.txt',line:7,name:'../bad'}),/slug/);
assert.throws(()=>call('search',{query:'x',limit:101}),/Limit/);
assert.throws(()=>call('search',{query:'x',folder:'does-not-exist'}),/folder was not found/);
const saved = call('save',{file:'missions/example.txt',line:7,name:'event-from-mission',notes:'Demonstrates a mission firing an event; verify timing in game.'});
assert.ok(fs.existsSync(saved.savedGuide)); assert.match(fs.readFileSync(saved.savedGuide,'utf8'),/not playtested/);
assert.equal(call('list',{}).results.length,1);
assert.equal(call('verify',{}).results[0].reviewRequired,false);
assert.throws(()=>call('save',{file:'missions/example.txt',line:7,name:'event-from-mission'}),/already exists/);
assert.equal(call('docs',{query:'event firing'}).totalMatches,0);
assert.ok(call('docs',{query:'mission firing'}).totalMatches>0);
fs.appendFileSync(path.join(game,'missions/example.txt'),'# unrelated new comment\n');
const changed = call('verify',{}).results[0];
assert.equal(changed.reviewRequired,true); assert.equal(changed.excerptMatchesAtRecordedLines,true);
put(path.join(game,'launcher-settings.json'),JSON.stringify({rawVersion:'v1.38.0'}));
assert.equal(call('verify',{}).results[0].versionMatches,false);
put(path.join(game,'common/legacy.txt'),Buffer.from([0x23,0x20,0xe9,0x0a,0x61,0x20,0x3d,0x20,0x7b,0x7d]));
assert.equal(call('search',{query:'a =',folder:'common'}).results[0].encoding,'Windows-1252 fallback');
console.log('PASS: literal/identifier search, folder filters, block context, truncation, saved documentation, version/hash freshness, overwrite/path protection and legacy encoding.');
