import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { inventory, fileChecks, consolidate, compare, classify, deploymentPreparation, evidence, checkProject } from './check.mjs';
import { identity, buildIdentity, cwtoolsIdentity } from '../evidence-identity.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const fixture = path.join(here, 'test-work', crypto.randomUUID());
const root = path.join(fixture, 'workspace'), source = path.join(root, 'mod/fixture'), storage = path.join(fixture, 'reports');
const put = (file, bytes) => { fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, bytes); };
const json = (file, data) => put(file, JSON.stringify(data));
const yml = path.join(source, 'localisation/english/example_l_english.yml');
put(yml, Buffer.concat([Buffer.from([0xef, 0xbb, 0xbf]), Buffer.from('l_english:\n example:0 "Title"\n')]));
put(path.join(source, 'missions/example.txt'), 'example = { slot = 1 }');
assert.deepEqual(fileChecks(source, inventory(source)), []);
put(yml, 'l_french:\n');
let codes = fileChecks(source, inventory(source)).map(item => item.code);
assert.ok(codes.includes('localisation-bom')); assert.ok(codes.includes('localisation-header'));
put(yml, Buffer.from([0xef, 0xbb, 0xbf, 0xff]));
assert.ok(fileChecks(source, inventory(source)).some(item => item.code === 'localisation-utf8'));
put(yml, Buffer.concat([Buffer.from([0xef, 0xbb, 0xbf]), Buffer.from('l_english:\n')]));
put(path.join(source, 'tests/test.py'), 'fixture');
put(path.join(source, 'bad.txt'), Buffer.from([0xff, 0xfe, 0, 0]));
codes = fileChecks(source, inventory(source)).map(item => item.code);
assert.ok(codes.includes('development-file')); assert.ok(codes.includes('unsupported-encoding'));
fs.unlinkSync(path.join(source, 'tests/test.py')); fs.rmdirSync(path.join(source, 'tests')); fs.unlinkSync(path.join(source, 'bad.txt'));
const gameMods = path.join(fixture, 'game-mods'); fs.mkdirSync(gameMods);
json(path.join(root, 'tools/deployment/config.json'), { gameModDirectory: gameMods, supportedVersion: '1.37.*' });
const prepared = deploymentPreparation(root, 'fixture', inventory(source));
assert.equal(prepared.findings.length, 0); assert.match(prepared.descriptor, /fixture \(Development\)/);
assert.equal(fs.readdirSync(gameMods).length, 0, 'Preparation wrote game files');
fs.mkdirSync(prepared.target);
assert.equal(deploymentPreparation(root, 'fixture', inventory(source)).findings[0].code, 'unowned-destination');
fs.rmdirSync(prepared.target);
// Identity cannot be normalized from matching bytes or selected storage alone.
// These files and records are confined to the unique synthetic self-test root.
fs.mkdirSync(prepared.target);
put(path.join(prepared.target,'descriptor.mod'),prepared.descriptor);
put(prepared.launcher,prepared.launcherText);
const deploymentKey=crypto.createHash('sha256').update(prepared.target.toLowerCase()).digest('hex').slice(0,16);
const deploymentRecordPath=path.join(root,`tools/deployment/state/fixture/${deploymentKey}/latest.json`);
const deploymentRecord={schemaVersion:2,sourceMod:null,storageNamespace:'fixture',artifactKind:'staged',target:prepared.target,launcher:prepared.launcher,
 files:inventory(prepared.target).files,launcherSha256:prepared.launcherSha256};
json(deploymentRecordPath,deploymentRecord);
assert.equal(deploymentPreparation(root,'fixture',inventory(source)).findings.length,0);
for(const conflict of [{sourceMod:'american_century'},{storageNamespace:'other'},{artifactKind:'production'},{schemaVersion:99}]) {
 json(deploymentRecordPath,{...deploymentRecord,...conflict});
 assert.ok(deploymentPreparation(root,'fixture',inventory(source)).findings.some(f=>['identity-conflict','unsupported-schema'].includes(f.code)));
}
const legacyDeployment={...deploymentRecord};delete legacyDeployment.schemaVersion;delete legacyDeployment.sourceMod;
json(deploymentRecordPath,legacyDeployment);
assert.equal(deploymentPreparation(root,'fixture',inventory(source)).findings.length,0);
fs.unlinkSync(path.join(prepared.target,'descriptor.mod'));fs.rmdirSync(prepared.target);fs.unlinkSync(prepared.launcher);
const finding = { tool: 'cwtools', severity: 'error', code: 'CW1', file: 'missions/example.txt', message: 'Undefined reference' };
const grouped = consolidate([{ ...finding, line: 1 }, { ...finding, line: 2 }]);
assert.equal(grouped.length, 1); assert.equal(grouped[0].occurrences.length, 2);
const shifted = consolidate([{ ...finding, line: 100 }]);
assert.equal(shifted[0].id, grouped[0].id);
assert.equal(compare(shifted, { findings: grouped }, ['cwtools']).occurrenceChanges.length, 1);
assert.equal(compare([], { findings: grouped }, []).resolved.length, 0);
assert.equal(compare([], { findings: grouped }, []).deferred.length, 1);
assert.equal(classify([{ status: 'complete', errors: 1 }, { status: 'incomplete' }]), 'incomplete');
json(path.join(root, 'tools/cwtools/config.json'), { timeoutSeconds: 1 });
const validatorReport = path.join(root, 'tools/cwtools/reports/fixture/latest.json');
const validator = diagnostics => async () => {
  json(validatorReport, { ...cwtoolsIdentity({root,project:source}),artifactBuild:buildIdentity(source),startedAtUtc:new Date().toISOString(),finishedAtUtc:new Date().toISOString(),status: 'complete', validatedAt: new Date().toISOString(), project: source, summary: { errors: diagnostics.filter(item => item.severity === 'error').length }, diagnostics });
  return { exitCode: diagnostics.some(item => item.severity === 'error') ? 1 : 0, output: 'fixture validator' };
};
const inspector = issues => () => ({ identity:{...identity({sourceMod:null,storageNamespace:'fixture',artifactKind:'fixture',evidenceSource:'static',coveredLayers:['STATIC'],artifactBuild:buildIdentity(source)}),status:'complete',startedAtUtc:new Date().toISOString(),finishedAtUtc:new Date().toISOString()},reports: [{ scenario: { name: 'normal' }, findings: issues }, { scenario: { name: 'diagnostic', diagnostic: true }, findings: [{ severity: 'error', code: 'conflicting-state', message: 'deliberately invalid' }] }] });
const layoutError = { severity: 'error', code: 'overlap', message: 'Two missions overlap', missions: ['a', 'b'] };
const invoke = opts => checkProject('fixture', { root, storage, ...opts });
const first = await invoke({ validator: validator([finding]), inspector: inspector([layoutError]) });
assert.equal(first.exitCode, 1); assert.equal(first.report.comparison.new.length, 2);
const interrupted = await invoke({ validator: async () => ({ exitCode: 2, error: 'timeout fixture' }), inspector: inspector([]) });
assert.equal(interrupted.exitCode, 2); assert.equal(interrupted.report.comparison.deferred.length, 1); assert.equal(interrupted.report.comparison.resolved.length, 1);
assert.equal(JSON.parse(fs.readFileSync(path.join(storage, 'fixture/last-complete.json'))).finishedAtUtc, first.report.finishedAtUtc);
const stale = await invoke({ validator: async () => { const old = JSON.parse(fs.readFileSync(validatorReport)); old.validatedAt = '2000-01-01T00:00:00Z'; json(validatorReport, old); return { exitCode: 1 }; }, inspector: inspector([]) });
assert.equal(stale.exitCode, 2); assert.match(stale.report.checks[0].message, /stale/);
const fixed = await invoke({ validator: validator([]), inspector: inspector([]) });
assert.equal(fixed.exitCode, 0); assert.equal(fixed.report.comparison.resolved.length, 2);
assert.equal(fixed.report.gameEvidence.status, 'none');
const logRun = path.join(root, 'tools/test-runs/reports/fixture/test-run');
const logReport = { outcome: 'failed', scenario: 'fixture scenario', deploymentChanges: [], changedLogs: 1 };
const logMetadata = { id: 'test-run', status: 'complete', deployment: { record: { files: prepared.preparedFiles, launcherSha256: prepared.launcherSha256 } } };
json(path.join(logRun, 'report.json'), logReport); json(path.join(logRun, 'run.json'), logMetadata);
json(path.join(root, 'tools/test-runs/reports/fixture/latest.json'), { report: path.join(logRun, 'report.json') });
assert.equal(evidence(root, 'fixture', prepared).status, 'unavailable','Ambiguous legacy fixture must not become production evidence');
const explicitIdentity={...identity({sourceMod:null,storageNamespace:'fixture',artifactKind:'staged',sourceBuild:buildIdentity(source),evidenceSource:'operator',coveredLayers:[],runId:'test-run'}),startedAtUtc:new Date().toISOString(),finishedAtUtc:new Date().toISOString()};
json(path.join(logRun,'run.json'),{...logMetadata,...explicitIdentity});
json(path.join(logRun,'report.json'),{...logReport,...explicitIdentity});
assert.equal(evidence(root, 'fixture', prepared).status, 'matching-build');
assert.equal(evidence(root, 'fixture', prepared).outcome, 'failed', 'Operator outcome was discarded');
assert.equal(evidence(root, 'fixture', { ...prepared, preparedFiles: [] }).status, 'stale');
json(path.join(logRun, 'report.json'), { ...logReport,...explicitIdentity, deploymentChanges: ['mission changed'] });
assert.equal(evidence(root, 'fixture', prepared).status, 'stale');
json(path.join(logRun, 'run.json'), { ...logMetadata, deployment: null });
assert.equal(evidence(root, 'fixture', prepared).status, 'untracked');
json(path.join(logRun, 'run.json'), { ...logMetadata, status: 'running' });
assert.equal(evidence(root, 'fixture', prepared).status, 'unavailable');
const changed = await invoke({ validator: async () => { fs.appendFileSync(path.join(source, 'missions/example.txt'), '\n# changed'); return validator([])(); }, inspector: inspector([]) });
assert.equal(changed.exitCode, 2); assert.ok(changed.report.checks.every(item => item.status === 'incomplete'));
assert.equal(fs.readdirSync(gameMods).length, 0, 'Project checker changed game directory');
assert.equal(fs.existsSync(path.join(storage, 'fixture/active.lock')), false);
put(path.join(storage, 'fixture/active.lock'), 'fixture lock');
await assert.rejects(invoke({ validator: validator([]), inspector: inspector([]) }), /already active/);
console.log('PASS: encodings, development files, deployment preparation, finding grouping, incomplete/stale validation, resolution history, diagnostic exclusion, gameplay build evidence, source changes, concurrency and no game writes.');
